# Welcome to Jekyll!
#
# view it on local site: http://localhost:4000/birthday-assist/
title: 生日助手
author: uniqueWTS
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  It's a web application designed to assist users to memorize birthdays for a better social relationship.

baseurl: "/birthday-assist" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  uniqueWTS

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
